using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DietTime.Persistence.Migrations;

[DbContext(typeof(DietTimeDbContext))]
[Migration("202607140001_IdentityAndRefreshTokens")]
public sealed class IdentityAndRefreshTokens : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE TABLE IF NOT EXISTS "AspNetRoles" (id uuid PRIMARY KEY, name varchar(256), normalized_name varchar(256), concurrency_stamp text);
        CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" (normalized_name);
        CREATE TABLE IF NOT EXISTS "AspNetUsers" (id uuid PRIMARY KEY, user_name varchar(256), normalized_user_name varchar(256), email varchar(256), normalized_email varchar(256), email_confirmed boolean NOT NULL, password_hash text, security_stamp text, concurrency_stamp text, phone_number text, phone_number_confirmed boolean NOT NULL, two_factor_enabled boolean NOT NULL, lockout_end timestamptz, lockout_enabled boolean NOT NULL, access_failed_count integer NOT NULL);
        CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" (normalized_user_name);
        CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" (normalized_email);
        CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id uuid NOT NULL REFERENCES "AspNetRoles"(id) ON DELETE CASCADE, claim_type text, claim_value text);
        CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_role_id" ON "AspNetRoleClaims" (role_id);
        CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id uuid NOT NULL REFERENCES "AspNetUsers"(id) ON DELETE CASCADE, claim_type text, claim_value text);
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_user_id" ON "AspNetUserClaims" (user_id);
        CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (login_provider varchar(128) NOT NULL, provider_key varchar(128) NOT NULL, provider_display_name text, user_id uuid NOT NULL REFERENCES "AspNetUsers"(id) ON DELETE CASCADE, PRIMARY KEY (login_provider, provider_key));
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_user_id" ON "AspNetUserLogins" (user_id);
        CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (user_id uuid NOT NULL REFERENCES "AspNetUsers"(id) ON DELETE CASCADE, role_id uuid NOT NULL REFERENCES "AspNetRoles"(id) ON DELETE CASCADE, PRIMARY KEY (user_id, role_id));
        CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_role_id" ON "AspNetUserRoles" (role_id);
        CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (user_id uuid NOT NULL REFERENCES "AspNetUsers"(id) ON DELETE CASCADE, login_provider varchar(128) NOT NULL, name varchar(128) NOT NULL, value text, PRIMARY KEY (user_id, login_provider, name));
        CREATE TABLE IF NOT EXISTS refresh_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES "AspNetUsers"(id) ON DELETE CASCADE, token_hash varchar(64) NOT NULL, created_at timestamptz NOT NULL, expires_at timestamptz NOT NULL, revoked_at timestamptz);
        CREATE UNIQUE INDEX IF NOT EXISTS ix_refresh_tokens_token_hash ON refresh_tokens(token_hash);
        CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens(user_id);
        """);

    protected override void Down(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        DROP TABLE IF EXISTS refresh_tokens;
        DROP TABLE IF EXISTS "AspNetUserTokens";
        DROP TABLE IF EXISTS "AspNetUserRoles";
        DROP TABLE IF EXISTS "AspNetUserLogins";
        DROP TABLE IF EXISTS "AspNetUserClaims";
        DROP TABLE IF EXISTS "AspNetRoleClaims";
        DROP TABLE IF EXISTS "AspNetUsers";
        DROP TABLE IF EXISTS "AspNetRoles";
        """);
}
