using DietTime.Domain;
using DietTime.Application;
using DietTime.Contracts;
using DietTime.Persistence;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using System.Net;
using System.Net.Http.Json;
using Testcontainers.PostgreSql;

namespace DietTime.Meal.Api.IntegrationTests;

public sealed class CatalogueApiTests : IAsyncLifetime
{
    private readonly bool enabled = Environment.GetEnvironmentVariable("RUN_INTEGRATION_TESTS") == "true";
    private PostgreSqlContainer? postgres;
    private ApiFactory? factory; private HttpClient? client; private Guid planId; private Guid dayId; private Guid wednesdayDayId; private Guid mealId;
    public async Task InitializeAsync() { if (!enabled) return; postgres = new PostgreSqlBuilder().WithImage("postgres:16-alpine").WithDatabase("diettime_test").WithUsername("postgres").WithPassword("postgres").Build(); await postgres.StartAsync(); factory = new(postgres.GetConnectionString()); client = factory.CreateClient(); await SeedAsync(); }
    public async Task DisposeAsync() { client?.Dispose(); if (factory is not null) await factory.DisposeAsync(); if (postgres is not null) await postgres.DisposeAsync(); }

    [Fact] public async Task Meal_list_returns_only_configured_slot_options() { if (!enabled) return; var response = await client!.GetAsync($"/api/v1/meal-plans/{planId}/meals?templateDayId={dayId}"); Assert.True(response.IsSuccessStatusCode); Assert.Contains("DT-BRK-0001", await response.Content.ReadAsStringAsync()); }
    [Fact] public async Task Meal_list_filters_by_meal_type() { if (!enabled) return; Assert.True((await client!.GetAsync($"/api/v1/meal-plans/{planId}/meals?templateDayId={dayId}&mealType=BREAKFAST")).IsSuccessStatusCode); }
    [Fact] public async Task Meal_list_filters_by_plan_and_day() { if (!enabled) return; var body = await client!.GetStringAsync($"/api/v1/meal-plans/{planId}/meals?templateDayId={dayId}"); Assert.Contains(mealId.ToString(), body, StringComparison.OrdinalIgnoreCase); }
    [Fact] public async Task Meal_response_is_localized() { if (!enabled) return; var body = await client!.GetStringAsync($"/api/v1/meals/{mealId}?language=ar"); Assert.Contains("وجبة", body); }
    [Fact] public async Task Meal_details_returns_active_meal() { if (!enabled) return; Assert.True((await client!.GetAsync($"/api/v1/meals/{mealId}")).IsSuccessStatusCode); }
    [Fact] public async Task Missing_meal_returns_404() { if (!enabled) return; Assert.Equal(System.Net.HttpStatusCode.NotFound, (await client!.GetAsync($"/api/v1/meals/{Guid.NewGuid()}")).StatusCode); }
    [Fact] public async Task Inactive_meal_is_excluded() { if (!enabled) return; using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); var meal = await db.MealItems.FindAsync(mealId); meal!.Status = "INACTIVE"; await db.SaveChangesAsync(); Assert.Equal(System.Net.HttpStatusCode.NotFound, (await client!.GetAsync($"/api/v1/meals/{mealId}")).StatusCode); }
    [Fact] public async Task Unpublished_plan_is_excluded() { if (!enabled) return; using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); var plan = await db.MealPlanTemplates.FindAsync(planId); plan!.IsPublished = false; await db.SaveChangesAsync(); Assert.Equal(System.Net.HttpStatusCode.NotFound, (await client!.GetAsync($"/api/v1/meal-plans/{planId}")).StatusCode); }
    [Fact] public async Task Template_days_are_ordered_and_use_uppercase_weekdays() { if (!enabled) return; var body = await client!.GetStringAsync($"/api/meal-plan-templates/{planId}/days"); Assert.True(body.IndexOf("WEDNESDAY", StringComparison.Ordinal) < body.IndexOf("THURSDAY", StringComparison.Ordinal)); Assert.DoesNotContain("dayNumber", body); }
    [Fact] public async Task Creating_weekday_menu_succeeds() { if (!enabled) return; var response = await client!.PostAsJsonAsync($"/api/meal-plan-templates/{planId}/days", new { menuWeekday = "SUNDAY", displayOrder = 2, isActive = true }); Assert.Equal(HttpStatusCode.Created, response.StatusCode); Assert.Contains("id", await response.Content.ReadAsStringAsync()); }
    [Fact] public async Task Creating_duplicate_weekday_returns_clear_conflict() { if (!enabled) return; var response = await client!.PostAsJsonAsync($"/api/meal-plan-templates/{planId}/days", new { menuWeekday = "WEDNESDAY", displayOrder = 5, isActive = true }); Assert.Equal(HttpStatusCode.Conflict, response.StatusCode); Assert.Contains("DUPLICATE_TEMPLATE_WEEKDAY", await response.Content.ReadAsStringAsync()); }
    [Fact] public async Task Wednesday_menu_contains_slots_and_options() { if (!enabled) return; var body = await client!.GetStringAsync($"/api/meal-plan-templates/{planId}/days/by-weekday/WEDNESDAY"); Assert.Contains(wednesdayDayId.ToString(), body, StringComparison.OrdinalIgnoreCase); Assert.Contains(mealId.ToString(), body, StringComparison.OrdinalIgnoreCase); Assert.Contains("minimumSelection", body); }
    [Fact] public async Task Deleting_template_day_soft_deactivates_without_deleting_slots() { if (!enabled) return; var response = await client!.DeleteAsync($"/api/meal-plan-templates/{planId}/days/{wednesdayDayId}"); Assert.Equal(HttpStatusCode.NoContent, response.StatusCode); using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); var day = await db.MealPlanTemplateDays.Include(x => x.Slots).ThenInclude(x => x.Options).SingleAsync(x => x.Id == wednesdayDayId); Assert.False(day.IsActive); Assert.NotEmpty(day.Slots); Assert.NotEmpty(day.Slots.Single().Options); }
    [Fact] public async Task Updating_active_meal_creates_latest_draft_version() { if (!enabled) return; using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); var source = await db.MealItems.Include(x => x.Translations).SingleAsync(x => x.Id == mealId); var request = new UpsertMealRequest(source.Sku, source.CategoryId, source.PreparationTimeMinutes, source.IsVegetarian, source.IsVegan, source.IsGlutenFree, source.IsDairyFree, source.IsAvailable, source.AvailableFrom, source.AvailableUntil, source.Translations.Select(x => new AdminTranslationRequest(x.LanguageCode, x.Name, x.ShortDescription, x.FullDescription)).ToArray(), null); var result = await scope.ServiceProvider.GetRequiredService<IAdminMealService>().UpdateMealAsync(mealId, request, null, default); Assert.NotNull(result); Assert.True(result.CreatedDraft); db.ChangeTracker.Clear(); var versions = await db.MealItems.Where(x => x.VersionGroupId == source.VersionGroupId).OrderBy(x => x.VersionNumber).ToListAsync(); Assert.Equal(2, versions.Count); Assert.Equal("ACTIVE", versions[0].Status); Assert.False(versions[0].IsLatest); Assert.Equal("DRAFT", versions[1].Status); Assert.True(versions[1].IsLatest); }
    [Fact] public async Task Updating_published_template_creates_latest_draft_version() { if (!enabled) return; using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); var source = await db.MealPlanTemplates.Include(x => x.Translations).SingleAsync(x => x.Id == planId); var request = new CreatePlanRequest(source.Code, source.PlanType, source.DurationDays, source.IsCustomizable, source.ValidFrom, source.ValidUntil, source.Translations.Select(x => new AdminTranslationRequest(x.LanguageCode, x.Name, x.ShortDescription, x.FullDescription)).ToArray()); var result = await scope.ServiceProvider.GetRequiredService<IAdminMealService>().UpdatePlanAsync(planId, request, null, default); Assert.NotNull(result); Assert.True(result.CreatedDraft); db.ChangeTracker.Clear(); var versions = await db.MealPlanTemplates.Include(x => x.Days).Where(x => x.VersionGroupId == source.VersionGroupId).OrderBy(x => x.VersionNumber).ToListAsync(); Assert.Equal(2, versions.Count); Assert.True(versions[0].IsPublished); Assert.False(versions[0].IsLatest); Assert.False(versions[1].IsPublished); Assert.True(versions[1].IsLatest); Assert.NotEmpty(versions[1].Days); }
    [Fact] public async Task Admin_meal_list_returns_price_category_and_nutrition() { if (!enabled) return; using var scope = factory!.Services.CreateScope(); var result = await scope.ServiceProvider.GetRequiredService<IAdminMealService>().GetMealsAsync(null, 1, 25, default); var meal = Assert.Single(result.Items); Assert.Equal("BREAKFAST", meal.Category.Code); Assert.Equal("Breakfast", meal.Category.Name); Assert.Equal(500, meal.Nutrition?.ServingQuantity); Assert.Equal(420, meal.Nutrition?.CaloriesKcal); Assert.Equal(25, meal.Price?.Amount); Assert.Equal("QAR", meal.Price?.CurrencyCode); }
    [Fact] public async Task Guest_home_is_public_and_returns_single_screen_payload() { if (!enabled) return; var response = await client!.GetAsync("/api/v1/guest/home?date=2026-07-23"); Assert.Equal(HttpStatusCode.OK, response.StatusCode); var body = await response.Content.ReadAsStringAsync(); Assert.DoesNotContain("\"hero\"", body); Assert.Contains("\"mealPlans\"", body); Assert.Contains("\"description\":\"Classic short description\"", body); Assert.Contains("\"imageUrl\":\"https://cdn.test/plan.png\"", body); Assert.Contains("\"weeklyCalendar\"", body); Assert.Contains("\"mealTimeFilters\"", body); Assert.Contains("\"meals\"", body); Assert.Contains("\"pagination\"", body); }
    [Fact] public async Task Guest_home_localizes_arabic_and_falls_back_to_english() { if (!enabled) return; var body = await client!.GetStringAsync("/api/v1/guest/home?date=2026-07-23&language=ar"); Assert.Contains("ÙˆØ¬Ø¨Ø©", body); Assert.Contains("\"description\":\"Arabic plan short description\"", body); }
    [Fact] public async Task Guest_home_filters_meal_time_and_paginates() { if (!enabled) return; var body = await client!.GetStringAsync("/api/v1/guest/home?date=2026-07-23&mealTimeCode=BREAKFAST&page=1&pageSize=1"); Assert.Contains(mealId.ToString(), body, StringComparison.OrdinalIgnoreCase); Assert.Contains("\"totalRecords\":1", body); Assert.Contains("\"hasNextPage\":false", body); }
    [Theory] [InlineData("language=fr")] [InlineData("mealTimeCode=BRUNCH")] [InlineData("page=0")] [InlineData("pageSize=101")] public async Task Guest_home_rejects_invalid_parameters(string query) { if (!enabled) return; Assert.Equal(HttpStatusCode.BadRequest, (await client!.GetAsync($"/api/v1/guest/home?{query}")).StatusCode); }
    [Fact] public async Task Guest_home_returns_404_when_selected_date_has_no_menu() { if (!enabled) return; Assert.Equal(HttpStatusCode.NotFound, (await client!.GetAsync("/api/v1/guest/home?date=2026-07-24")).StatusCode); }

    private async Task SeedAsync()
    {
        using var scope = factory!.Services.CreateScope(); var db = scope.ServiceProvider.GetRequiredService<DietTimeDbContext>(); await db.Database.EnsureCreatedAsync(); var now = DateTimeOffset.UtcNow;
        var category = new MealCategory { Code = "BREAKFAST", IsActive = true, CreatedAt = now, UpdatedAt = now, RowVersion = 1, Translations = [new() { LanguageCode = "en", Name = "Breakfast", CreatedAt = now, UpdatedAt = now }] };
        var type = new MealType { Code = "BREAKFAST", IsActive = true, DisplayOrder = 1, CreatedAt = now, UpdatedAt = now, Translations = [new() { LanguageCode = "en", Name = "Breakfast", CreatedAt = now, UpdatedAt = now }, new() { LanguageCode = "ar", Name = "الإفطار", CreatedAt = now, UpdatedAt = now }] };
        var meal = new MealItem { Sku = "DT-BRK-0001", Category = category, Status = "ACTIVE", IsAvailable = true, CreatedAt = now, UpdatedAt = now, RowVersion = 1, Translations = [new() { LanguageCode = "en", Name = "Test Meal", CreatedAt = now, UpdatedAt = now }, new() { LanguageCode = "ar", Name = "وجبة تجريبية", CreatedAt = now, UpdatedAt = now }], Nutrition = new() { ServingQuantity = 500, ServingUnit = "g", CaloriesKcal = 420, ProteinGrams = 35, CarbohydratesGrams = 40, FatGrams = 12, CreatedAt = now, UpdatedAt = now }, Prices = [new() { PriceType = "INDIVIDUAL", CurrencyCode = "QAR", Amount = 25, EffectiveFrom = now.AddDays(-1), IsActive = true, CreatedAt = now, UpdatedAt = now }] }; mealId = meal.Id = Guid.NewGuid(); meal.VersionGroupId = mealId;
        var plan = new MealPlanTemplate { Code = "CLASSIC", PlanType = "STANDARD", DurationDays = 7, IsActive = true, IsPublished = true, IsCustomizable = true, CreatedAt = now, UpdatedAt = now, RowVersion = 1, Translations = [new() { LanguageCode = "en", Name = "Classic", ShortDescription = "Classic short description", CreatedAt = now, UpdatedAt = now }, new() { LanguageCode = "ar", Name = "Arabic Classic", ShortDescription = "Arabic plan short description", CreatedAt = now, UpdatedAt = now }] }; planId = plan.Id = Guid.NewGuid(); plan.VersionGroupId = planId;
        var day = new MealPlanTemplateDay { Plan = plan, MenuWeekday = MenuWeekday.Thursday, DisplayOrder = 6, IsActive = true, CreatedAt = now, UpdatedAt = now }; dayId = day.Id = Guid.NewGuid(); var slot = new MealPlanTemplateSlot { Day = day, MealType = type, MinimumSelection = 1, MaximumSelection = 1, IsRequired = true, AllowsPaidUpgrade = true, IsActive = true, CreatedAt = now, UpdatedAt = now, RowVersion = 1 }; slot.Options.Add(new() { MealItem = meal, IsAvailable = true, CreatedAt = now, UpdatedAt = now });
        var wednesday = new MealPlanTemplateDay { Plan = plan, MenuWeekday = MenuWeekday.Wednesday, DisplayOrder = 5, IsActive = true, CreatedAt = now, UpdatedAt = now }; wednesdayDayId = wednesday.Id = Guid.NewGuid(); var wednesdaySlot = new MealPlanTemplateSlot { Day = wednesday, MealType = type, DisplayOrder = 1, MinimumSelection = 1, MaximumSelection = 1, IsRequired = true, AllowsPaidUpgrade = true, IsActive = true, CreatedAt = now, UpdatedAt = now, RowVersion = 1 }; wednesdaySlot.Options.Add(new() { MealItem = meal, IsAvailable = true, IsDefault = true, CreatedAt = now, UpdatedAt = now });
        db.Add(plan); db.MealMedia.Add(new() { EntityId = planId, MediaType = MealMediaTypes.MealPlan, ObjectKey = $"meal-plans/{planId:D}/images/plan.png", PublicUrl = "https://cdn.test/plan.png", IsPrimary = true, Status = "ACTIVE", CreatedAt = now, UpdatedAt = now }); await db.SaveChangesAsync();
    }
}

internal sealed class ApiFactory(string connectionString) : WebApplicationFactory<Program>
{
    protected override void ConfigureWebHost(IWebHostBuilder builder) => builder.ConfigureAppConfiguration((_, config) => config.AddInMemoryCollection(new Dictionary<string, string?> { ["ConnectionStrings:DefaultConnection"] = connectionString, ["Jwt:Issuer"] = "DietTime.Tests", ["Jwt:Audience"] = "DietTime.Tests", ["Jwt:Key"] = "test-only-key-at-least-thirty-two-characters-long", ["Storage:PublicBaseUrl"] = "https://cdn.test", ["Storage:BucketName"] = "test", ["Storage:ServiceUrl"] = "http://localhost:9000", ["Storage:AccessKey"] = "test", ["Storage:SecretKey"] = "test" }));
}
